### ISSUE TITLE
TextView 自身折行的问题

### ISSUE THREAD

**Issue by 29995270** [dinuscxj/EllipsizeTextView#1]
不知道作者有没有碰到过这种需求，
在几行文字的最后 加上 '...更多'，要求这几个文字要gravity end显示，但是由于 TextView 会对连续的英文在剩余空间不够显示的时候自动折行，导致 Ellipsize 文字被连接到了 最后一行的中间。
比如以下代码就会造成类似情况

`  

```
    mTvEllipsize0.setEllipsizeText(moreText, 0);
    mTvEllipsize0.setText(
            "The EllipsizeTextView offers a lot of flexibility when it someStringToLongWillNotBeBreakInTextView in the text " +
                    "that are longer than the view is wide to be omitted instead of broken in the middle.");`
```

someStringToLongWillNotBeBreakInTextView 这个词放在合适的位置就会让 textview 折行。

不知道您对这类问题有什么好的解决方法。

**Comment by dinuscxj** [comment]
@29995270 你说的这个跟TextView里面管理布局的StaticLayout有关，  通过单词大小决定换行, 单词的分割符 包括 '\t',  ' ',   '\u200B'这三个。 同时布局文件是每次布局管理器都是动态new的，很难管理这种换行的。 我感觉如果非要实现你的这种效果， 需要动态插入换行符才可能实现， 而且控制起来比较复杂！
