### ISSUE TITLE
能不设置maxLine么，当text太多时自动显示...

### ISSUE THREAD

**Issue by hackware1993** [dinuscxj/EllipsizeTextView#2]

**Comment by dinuscxj** [comment]
不设置maxline， 无法确定在第几行显示...   自动显示也是需要有依据的呀！

**Comment by hackware1993** [comment]
@dinuscxj 自己计算啊，不然你这个东西有什么优势呢，TextView原生就支持啊

**Comment by dinuscxj** [comment]
@hackware1993 优势在于自定义省略符号样式， 支持自定义省略符号的位置， 支持CharacterStyle样式不被截取一半， 而且解决了TextView在不同手机上支持多行存在的问题！

**Comment by dinuscxj** [comment]
@hackware1993 比如让你做一个： 很长的问题＋时间（时间长度不定）， 产品要求你最多显示两行， 且省略符号的样式是 "...更多" 且在时间之前， 同时点击更多，展开全部内容！ 你就知道这个的用意了

**Comment by dinuscxj** [comment]
@hackware1993 而且产品要求如果结尾的是 ‘@dinus_cxj’ 则要么全部显示， 要么不显示， 并且不能有emoji截断， （其实我说的就是我所在公司的需求）

**Comment by hackware1993** [comment]
@dinuscxj 如果textview的宽高是固定的，则默认情况下，文字过多会被切掉，可以通过自己计算行数来设置…，无需设置maxLine，因为有时候maxLine是未知的

**Comment by dinuscxj** [comment]
@hackware1993 这个确实值得考虑， 我在判断省略符号的条件上加上在定高并且layout.getHeight() > getMeasureHeight() - getPaddingtop() - getPaddingBottom()应该就可以啦！ tks

**Comment by hackware1993** [comment]
@dinuscxj 你想多了，getMeasuredHeight和getHeight一般都是相等的

**Comment by dinuscxj** [comment]
@hackware1993  Layout.getHeight() 不是View.getHeight() 这个layout是通过TextView.getLayout()获取的,😅。 你好好看一下代码就懂了！

**Comment by hackware1993** [comment]
@dinuscxj 对，这样才可行

**Comment by hackware1993** [comment]
```
@Override
protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
    super.onLayout(changed, left, top, right, bottom);
    Layout layout = getLayout();
    if (layout != null) {
        int viewportHeight = getHeight() - getPaddingTop() - getPaddingBottom();
        if (layout.getHeight() > viewportHeight) {
            for (int i = 0, j = layout.getLineCount(); i < j; i++) {
                int lineBottom = layout.getLineBottom(i);
                if (lineBottom > viewportHeight) {
                    setEllipsize(TextUtils.TruncateAt.END);
                    setMaxLines(i);
                    break;
                }
            }
        }
    }
}
```

**Comment by dinuscxj** [comment]
@hackware1993 这种写法有很多问题的！ 解决不了@人 被截取， 同时也解决不了部分手机对于Ellipsize的支持，当然样式也不可定制！

**Comment by dinuscxj** [comment]
@hackware1993  我昨天晚上12点的时候， 已经把支持自动模式的代码推倒了jcenter  1.0.1是支持自动模式的

**Comment by hackware1993** [comment]
@dinuscxj 我的需求没你那么复杂，只是文本显示不下时显示...，TextView的宽高都是match_parent，是没法设置一个确定的maxLines
