### ISSUE TITLE
Gradle Library not found

### ISSUE THREAD

**Issue by ericntd** [dinuscxj/EllipsizeTextView#4]
Is it not on Maven Central? I could not find it on JCenter() either
If not, where can I fine it? 😄

**Comment by dinuscxj** [comment]
I have pushed the gradle dependencies to the JCenter, I can't figure out why not be used !
you can copy the [file](https://github.com/dinuscxj/EllipsizeTextView/blob/master/ellipsizetextview/src/main/java/com/dinuscxj/ellipsize/EllipsizeTextView.java) to your project!

**Comment by ericntd** [comment]
![screen shot 2016-10-06 at 9 45 35 am](https://cloud.githubusercontent.com/assets/19919208/19137869/ae64721c-8ba9-11e6-9f41-ca0c15b170c2.png)

**Comment by dinuscxj** [comment]
<img width="813" alt="5bf7b20a-49f0-4d73-b8c1-6c166441de6f" src="https://cloud.githubusercontent.com/assets/14000274/19159899/8967111e-8c20-11e6-8bf4-72d76c031b20.png">

I forget to click the button "add to jcenter"
